version: '3'
services:
  jupyter_basic:
    build: .
    entrypoint: ./entrypoint.sh
    volumes:
      - notebooks:/notebooks
    ports:
      - "8889:8889"
volumes:
  notebooks:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${PWD}/notebooks